import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/shared/Header";
import Footer from "@/components/shared/Footer";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Zavisoft",
  description: "Generated by create next app with the new app directory structure.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
          <main className="bg-[#E7E7E3] min-h-screen">
          <div className="px-4 md:px-0">
            <Header />
          </div>
          <div className="md:pt-32 pt-20">
            {children}
            <ToastContainer position="top-right" autoClose={3000} />
          </div>
        <Footer />
        </main>
      </body>
    </html>
  );
}
